--일괄삭제
DROP TABLE EMP_RESUME;
DROP TABLE EMP_BOARD;
DROP TABLE EMP_MYPAGE;
DROP TABLE EMP_FAQ;
DROP TABLE EMP_INFO;



-- 개인 회원가입

CREATE TABLE EMP_INFO(
    MEM_EMAIL        VARCHAR2(20)     NOT NULL, 
    MEM_NICKNAME     VARCHAR2(20)     NOT NULL, 
    MEM_PASS         VARCHAR2(20)     NOT NULL, 
    MEM_NAME         VARCHAR2(20)     NOT NULL, 
    MEM_AGE          NUMBER           NOT NULL, 
    MEM_GENDER       VARCHAR2(10)     NULL, 
    MEM_BIRTH        NUMBER           NULL, 
    MEM_TEL1         NUMBER           NOT NULL, 
    MEM_TEL2         NUMBER           NULL, 
    MEM_ADDR         VARCHAR2(100)    NOT NULL, 
    MEM_MERRY        VARCHAR2(5)      NULL, 
    MEM_YN           VARCHAR2(5)      NULL, 
    MEM_PASS_HINT    VARCHAR2(50)     NOT NULL, 
    MEM_JOIN_DATE    DATE             NOT NULL, 
    CONSTRAINT EMP_INFO_PK PRIMARY KEY (MEM_EMAIL)
);

COMMENT ON TABLE EMP_INFO IS '개인회원(회원가입)';

COMMENT ON COLUMN EMP_INFO.MEM_EMAIL IS '이메일(아이디)';

COMMENT ON COLUMN EMP_INFO.MEM_NICKNAME IS '닉네임';

COMMENT ON COLUMN EMP_INFO.MEM_PASS IS '회원 비밀번호';

COMMENT ON COLUMN EMP_INFO.MEM_NAME IS '이름';

COMMENT ON COLUMN EMP_INFO.MEM_AGE IS '나이';

COMMENT ON COLUMN EMP_INFO.MEM_GENDER IS '성별';

COMMENT ON COLUMN EMP_INFO.MEM_BIRTH IS '생년월일';

COMMENT ON COLUMN EMP_INFO.MEM_TEL1 IS '연락처1(휴대폰)';

COMMENT ON COLUMN EMP_INFO.MEM_TEL2 IS '연락처2(집전화)';

COMMENT ON COLUMN EMP_INFO.MEM_ADDR IS '주소';

COMMENT ON COLUMN EMP_INFO.MEM_MERRY IS '결혼여부';

COMMENT ON COLUMN EMP_INFO.MEM_YN IS '회원탈퇴여부';

COMMENT ON COLUMN EMP_INFO.MEM_PASS_HINT IS '비밀번호힌트';

COMMENT ON COLUMN EMP_INFO.MEM_JOIN_DATE IS '가입날짜';

-------------------------------------------------------------------------------------

-- 이력서 모음
CREATE TABLE EMP_RESUME(
    RESUME_NUM         NUMBER           NOT NULL, 
    RESUME_TITLE       VARCHAR2(50)     NOT NULL, 
    RESUME_CONTENT     VARCHAR2(500)    NOT NULL, 
    MEM_EMAIL          VARCHAR2(20)     NOT NULL, 
    RESUME_ACADEMY     VARCHAR2(20)     NULL, 
    RESUME_CAREER      VARCHAR2(100)    NULL, 
    RESUME_LOC         VARCHAR2(100)    NULL, 
    RESUME_JOB         VARCHAR2(40)     NULL, 
    RESUME_TIME        VARCHAR2(20)     NULL, 
    RESUME_DATE        DATE             NULL, 
    RESUME_ANISAL      NUMBER           NULL, 
    RESUME_IMG         VARCHAR2(20)     NULL, 
    CERTIFICATION      VARCHAR2(500)    NULL, 
    RESUME_WISH_JOB    VARCHAR2(20)     NULL, 
    CONSTRAINT EMP_RESUME_PK PRIMARY KEY (RESUME_NUM),
    CONSTRAINT FK_EMP_RESUME_MEM_EMAIL_RE FOREIGN KEY (MEM_EMAIL) REFERENCES EMP_INFO (MEM_EMAIL)
);

COMMENT ON TABLE EMP_RESUME IS '이력서 모음';

COMMENT ON COLUMN EMP_RESUME.RESUME_NUM IS '이력서번호';

COMMENT ON COLUMN EMP_RESUME.RESUME_TITLE IS '이력서 제목';

COMMENT ON COLUMN EMP_RESUME.RESUME_CONTENT IS '이력서 내용';

COMMENT ON COLUMN EMP_RESUME.MEM_EMAIL IS '이메일(아이디)';

COMMENT ON COLUMN EMP_RESUME.RESUME_ACADEMY IS '학력사항';

COMMENT ON COLUMN EMP_RESUME.RESUME_CAREER IS '경력사항';

COMMENT ON COLUMN EMP_RESUME.RESUME_LOC IS '희망근무처';

COMMENT ON COLUMN EMP_RESUME.RESUME_JOB IS '희망 업직종';

COMMENT ON COLUMN EMP_RESUME.RESUME_TIME IS '희망 근무시간';

COMMENT ON COLUMN EMP_RESUME.RESUME_DATE IS '희망 근무기간';

COMMENT ON COLUMN EMP_RESUME.RESUME_ANISAL IS '희망 연봉';

COMMENT ON COLUMN EMP_RESUME.RESUME_IMG IS '첨부파일';

COMMENT ON COLUMN EMP_RESUME.CERTIFICATION IS '자격증';

COMMENT ON COLUMN EMP_RESUME.RESUME_WISH_JOB IS '관심직종';

----------------------------------------------------------------------------
-- 게시판

CREATE TABLE EMP_BOARD(
    REV_NUM           NUMBER          NOT NULL, 
    REV_TITLE         VARCHAR2(20)    NOT NULL, 
    REV_CONTENT       VARCHAR2(20)    NOT NULL, 
    REV_IMG_NAME      VARCHAR2(20)    NULL, 
    MEM_EMAIL         VARCHAR2(20)    NOT NULL, 
    REV_LOOK_CNT      NUMBER          NULL, 
    REV_WRITE_DATE    DATE            NOT NULL, 
    CONSTRAINT EMP_BOARD_PK PRIMARY KEY (REV_NUM),
    CONSTRAINT FK_EMP_BOARD_MEM_EMAIL_REC FOREIGN KEY (MEM_EMAIL) REFERENCES EMP_INFO (MEM_EMAIL)
);

COMMENT ON TABLE EMP_BOARD IS '개인회원 전용-기업 평가/경험담 작성 게시판(자유게시판)';

COMMENT ON COLUMN EMP_BOARD.REV_NUM IS '평가 글 번호';

COMMENT ON COLUMN EMP_BOARD.REV_TITLE IS '평가 제목';

COMMENT ON COLUMN EMP_BOARD.REV_CONTENT IS '평가 내용';

COMMENT ON COLUMN EMP_BOARD.REV_IMG_NAME IS '첨부파일';

COMMENT ON COLUMN EMP_BOARD.MEM_EMAIL IS '작성자';

COMMENT ON COLUMN EMP_BOARD.REV_LOOK_CNT IS '조회수';

COMMENT ON COLUMN EMP_BOARD.REV_WRITE_DATE IS '작성일';

----------------------------------------------------------------------------
-- 개인 마이페이지

CREATE TABLE EMP_MYPAGE(
    MEM_MYPAGE_NUM    NUMBER          NOT NULL, 
    MEM_EMAIL         VARCHAR2(20)    NOT NULL, 
    COM_NUM           VARCHAR2(30)    NULL, 
    CONSTRAINT EMP_MYPAGE_PK PRIMARY KEY (MEM_MYPAGE_NUM),
    CONSTRAINT FK_EMP_MYPAGE_MEM_E FOREIGN KEY (MEM_EMAIL) REFERENCES EMP_INFO (MEM_EMAIL)
);

COMMENT ON TABLE EMP_MYPAGE IS '회원이 선호하는 기업 장바구니';

COMMENT ON COLUMN EMP_MYPAGE.MEM_MYPAGE_NUM IS '마이페이지번호';

COMMENT ON COLUMN EMP_MYPAGE.MEM_EMAIL IS '이메일';

COMMENT ON COLUMN EMP_MYPAGE.COM_NUM IS '사업자번호';

----------------------------------------------------------------------------
-- 개인 문의글

CREATE TABLE EMP_FAQ(
    FAQ_NUM        NUMBER           NOT NULL, 
    FAQ_TYPE       VARCHAR2(20)     NOT NULL, 
    FAQ_CONTENT    VARCHAR2(20)     NOT NULL, 
    MEM_EMAIL      VARCHAR2(20)     NOT NULL, 
    MEM_TEL       NUMBER          NOT NULL, 
    FAQ_IMAGE      NVARCHAR2(20)    NULL, 
    FAQ_TITLE      VARCHAR2(20)     NOT NULL, 
    FAQ_DATE       DATE             NOT NULL, 
    FAQ_CHK        VARCHAR2(10)     NULL, 
    CONSTRAINT EMP_FAQ_PK PRIMARY KEY (FAQ_NUM),
    CONSTRAINT FK_EMP_FAQ_EMAIL FOREIGN KEY (MEM_EMAIL) REFERENCES EMP_INFO (MEM_EMAIL)
);

COMMENT ON TABLE EMP_FAQ IS '구직자 문의글';

COMMENT ON COLUMN EMP_FAQ.FAQ_NUM IS '문의번호';

COMMENT ON COLUMN EMP_FAQ.FAQ_TYPE IS '문의유형';

COMMENT ON COLUMN EMP_FAQ.FAQ_CONTENT IS '문의내용';

COMMENT ON COLUMN EMP_FAQ.MEM_EMAIL IS '작성자(회원 아이디)';

COMMENT ON COLUMN EMP_FAQ.MEM_TEL IS '연락처';

COMMENT ON COLUMN EMP_FAQ.FAQ_IMAGE IS '첨부파일';

COMMENT ON COLUMN EMP_FAQ.FAQ_TITLE IS '문의제목';

COMMENT ON COLUMN EMP_FAQ.FAQ_DATE IS '문의날짜';

COMMENT ON COLUMN EMP_FAQ.FAQ_CHK IS '처리상태';


