--일괄삭제
DROP TABLE ADMIN_PAGE;
DROP TABLE COM_IMAGE;

-- 관리자 페이지

CREATE TABLE ADMIN_PAGE(
    ADMIN_ID      VARCHAR2(20)    NOT NULL, 
    ADMIN_PASS    VARCHAR2(20)    NULL, 
    CONSTRAINT ADMIN_PAGE_PK PRIMARY KEY (ADMIN_ID)
);

COMMENT ON TABLE ADMIN_PAGE IS '관리자페이지';

COMMENT ON COLUMN ADMIN_PAGE.ADMIN_ID IS '관리자 아이디';

COMMENT ON COLUMN ADMIN_PAGE.ADMIN_PASS IS '관리자 비밀번호';

------------------------------------------------------------------------
-- 기업등록 이미지

CREATE TABLE COM_IMAGE(
    COM_IMG_ID      VARCHAR2(20)    NOT NULL, 
    COM_IMG_NAME    VARCHAR2(20)    NOT NULL, 
    CREATE_DATE     DATE            NOT NULL, 
    COM_NUM         VARCHAR2(30)    NOT NULL, 
    CONSTRAINT COM_IMAGE_PK PRIMARY KEY (COM_IMG_ID)
);


COMMENT ON TABLE COM_IMAGE IS '기업등록-사진/이미지';

COMMENT ON COLUMN COM_IMAGE.COM_IMG_ID IS '회사이미지 번호';

COMMENT ON COLUMN COM_IMAGE.COM_IMG_NAME IS '회사 사진이름';

COMMENT ON COLUMN COM_IMAGE.CREATE_DATE IS '사진생성날짜';

COMMENT ON COLUMN COM_IMAGE.COM_NUM IS '사업자번호';