--일괄삭제
DROP TABLE RECRUIT_LIST;
DROP TABLE COM_MYPAGE;
DROP TABLE APPLY_COM;
DROP TABLE COMPANY_INFO;

-- 기업정보

CREATE TABLE COMPANY_INFO(
    COM_NUM            VARCHAR2(30)     NOT NULL, 
    COM_PASS           VARCHAR2(50)     NOT NULL, 
    COM_EMAIL          VARCHAR2(60)     NOT NULL, 
    COM_NAME           VARCHAR2(30)     NOT NULL, 
    COM_CEO            VARCHAR2(20)     NOT NULL, 
    COM_LOC            VARCHAR2(200)    NOT NULL, 
    COM_TYPE           VARCHAR2(20)     NOT NULL, 
    COM_TEL            VARCHAR2(20)     NOT NULL, 
    COM_JOIN_DATE      DATE             DEFAULT SYSDATE, 
    COM_AVG_SCORE      NUMBER           DEFAULT 0, 
    COM_GIVE_PERSON    NUMBER           DEFAULT 0, 
    COM_SCORE          NUMBER           DEFAULT 0,
    COM_IMAGE           VARCHAR(50),
    CONSTRAINT COMPANY_INFO_PK PRIMARY KEY (COM_NUM)
);

COMMENT ON TABLE COMPANY_INFO IS '기업정보(회원가입)';

COMMENT ON COLUMN COMPANY_INFO.COM_NUM IS '사업자번호';

COMMENT ON COLUMN COMPANY_INFO.COM_PASS IS '비밀번호';

COMMENT ON COLUMN COMPANY_INFO.COM_EMAIL IS '이메일(아이디)';

COMMENT ON COLUMN COMPANY_INFO.COM_NAME IS '법인명';

COMMENT ON COLUMN COMPANY_INFO.COM_CEO IS '대표자명';

COMMENT ON COLUMN COMPANY_INFO.COM_LOC IS '본사 주소';

COMMENT ON COLUMN COMPANY_INFO.COM_TYPE IS '산업군';

COMMENT ON COLUMN COMPANY_INFO.COM_TEL IS '연락처';

COMMENT ON COLUMN COMPANY_INFO.COM_JOIN_DATE IS '가입날짜';

COMMENT ON COLUMN COMPANY_INFO.COM_AVG_SCORE IS '회사평균평점';

COMMENT ON COLUMN COMPANY_INFO.COM_GIVE_PERSON IS '평점 남긴 인원 수';

COMMENT ON COLUMN COMPANY_INFO.COM_SCORE IS '입력 받은 평점';

--------------------------------------------------------------------------------------

-- 채용공고

CREATE TABLE RECRUIT_LIST(
    ANNOUNCE_NUM        NUMBER           NOT NULL, 
    ANNOUNCE_TITLE      VARCHAR2(50)     NOT NULL, 
    ANNOUNCE_CONTENT    VARCHAR2(500)    NOT NULL, 
    WRITE_DATE          DATE             DEFAULT SYSDATE, 
    UPTO_HIREDATE       VARCHAR2(20)     NOT NULL, 
    HIRE_NUM            NUMBER           NOT NULL, 
    COM_NUM             VARCHAR2(30)     NOT NULL, 
    JOBTYPE             VARCHAR2(20)     NOT NULL, 
    WORKTIME            VARCHAR2(20)     NOT NULL, 
    WORK_TYPE           VARCHAR2(20)     NULL, 
    ANNI_SAL            NUMBER           NULL, 
    QUALIFICATION       VARCHAR2(100)    NULL, 
    BENEFIT             VARCHAR2(50)     NULL, 
    HIRE_CONDITION      VARCHAR2(10)     DEFAULT 'Y',
    REGIST_IMAGE        VARCHAR2(50),
    CAREER              VARCHAR2(50)    NOT NULL,
    ACADEMIC_BACKGROUND VARCHAR2(50)     NOT NULL,
    AREA                VARCHAR2(30)    NOT NULL,
    CONSTRAINT RECRUIT_LIST_PK PRIMARY KEY (ANNOUNCE_NUM),
     CONSTRAINT FK_RECRUIT_LIST_COM_NUM_RE FOREIGN KEY (COM_NUM) REFERENCES COMPANY_INFO (COM_NUM)
);
COMMENT ON TABLE RECRUIT_LIST IS '구인 게시판(채용공고)';

COMMENT ON COLUMN RECRUIT_LIST.ANNOUNCE_NUM IS '채용공고 번호';

COMMENT ON COLUMN RECRUIT_LIST.ANNOUNCE_TITLE IS '채용공고  제목';

COMMENT ON COLUMN RECRUIT_LIST.ANNOUNCE_CONTENT IS '채용공고  내용';

COMMENT ON COLUMN RECRUIT_LIST.WRITE_DATE IS '게시글 등록날짜';

COMMENT ON COLUMN RECRUIT_LIST.UPTO_HIREDATE IS '모집기간';

COMMENT ON COLUMN RECRUIT_LIST.HIRE_NUM IS '모집인원';

COMMENT ON COLUMN RECRUIT_LIST.COM_NUM IS '사업자번호';

COMMENT ON COLUMN RECRUIT_LIST.JOBTYPE IS '구인직종';

COMMENT ON COLUMN RECRUIT_LIST.WORKTIME IS '근무형태';

COMMENT ON COLUMN RECRUIT_LIST.WORK_TYPE IS '고용형태(계약/정규)';

COMMENT ON COLUMN RECRUIT_LIST.ANNI_SAL IS '연봉';

COMMENT ON COLUMN RECRUIT_LIST.QUALIFICATION IS '지원자격';

COMMENT ON COLUMN RECRUIT_LIST.BENEFIT IS '우대사항';

COMMENT ON COLUMN RECRUIT_LIST.HIRE_CONDITION IS '모집상태';

COMMENT ON COLUMN RECRUIT_LIST.CAREER IS '경력';

COMMENT ON COLUMN RECRUIT_LIST.ACADEMIC_BACKGROUND IS '학력';

COMMENT ON COLUMN RECRUIT_LIST.AREA IS '지역';


-------------------------------------------------------------------------

-- 지원 회사 목록

CREATE TABLE APPLY_COM(
    APPLY_NUM    NUMBER             NOT NULL, 
    MEM_EMAIL    VARCHAR2(20)    NOT NULL, 
    COM_NUM      VARCHAR2(30)    NOT NULL, 
    RESUME_RESULT       VARCHAR2(5)     NOT NULL, 
    CONSTRAINT APPLY_COM_PK PRIMARY KEY (APPLY_NUM),
    CONSTRAINT FK_APPLY_COM_NUM FOREIGN KEY (COM_NUM) REFERENCES COMPANY_INFO (COM_NUM)
);

COMMENT ON TABLE APPLY_COM IS '(회원)지원 회사 목록';

COMMENT ON COLUMN APPLY_COM.APPLY_NUM IS '지원회사 넘버';

COMMENT ON COLUMN APPLY_COM.MEM_EMAIL IS '이메일(아이디)';

COMMENT ON COLUMN APPLY_COM.COM_NUM IS '사업자번호';

COMMENT ON COLUMN APPLY_COM.RESUME_RESULT IS '합격여부';

----------------------------------------------------------------------------

-- 기업이 받은 지원이력서

CREATE TABLE COM_MYPAGE(
    COM_MYPAGE_NUM    NUMBER          NOT NULL, 
    COM_NUM           VARCHAR2(30)    NULL, 
    RESUME_NUM        NUMBER          NULL, 
    RESUME_RESULT     VARCHAR2(5)     NOT NULL, 
    CONSTRAINT COM_MYPAGE_PK PRIMARY KEY (COM_MYPAGE_NUM),
    CONSTRAINT FK_COM_MYPAGE_COM_NUM_RECRUIT_ FOREIGN KEY (COM_NUM) REFERENCES COMPANY_INFO (COM_NUM)
);

COMMENT ON TABLE COM_MYPAGE IS '기업이 받은 지원이력서';

COMMENT ON COLUMN COM_MYPAGE.COM_MYPAGE_NUM IS '마이페이지번호';

COMMENT ON COLUMN COM_MYPAGE.COM_NUM IS '사업자번호';

COMMENT ON COLUMN COM_MYPAGE.RESUME_NUM IS '이력서번호';

COMMENT ON COLUMN COM_MYPAGE.RESUME_RESULT IS '합격여부';




