--일괄삭제
DROP TABLE PROFILES;
DROP TABLE LICENSE;

DROP TABLE MEM_RESUME;

DROP TABLE MEM_INFO;

-- 개인 회원가입

CREATE TABLE MEM_INFO(
    MEM_EMAIL        VARCHAR2(100)    NOT NULL, 
    MEM_PASS         VARCHAR2(100)    NOT NULL, 
    MEM_NAME         VARCHAR2(100)    NOT NULL, 
    MEM_AGE          VARCHAR2(100)    NOT NULL,
    MEM_GENDER       VARCHAR2(100)    NOT NULL, 
    MEM_BIRTH        DATE            NOT NULL,
    MEM_TEL1         VARCHAR2(100)    NOT NULL, 
    MEM_TEL2         VARCHAR2(100)    NULL, 
    MEM_ADDR         VARCHAR2(100)   NOT NULL, 
    DEL_YN           VARCHAR2(100)    DEFAULT 'N',
    MEM_JOIN_DATE    DATE            DEFAULT SYSDATE,
    IS_ADMIN         VARCHAR(100)     DEFAULT 'N',
    MEM_IMAGE        VARCHAR(50)     NULL,
    CONSTRAINT MEM_INFO_PK PRIMARY KEY (MEM_EMAIL)
);

INSERT INTO MEM_INFO (MEM_GENDER, MEM_AGE, MEM_EMAIL, MEM_PASS, MEM_NAME, MEM_TEL1, MEM_ADDR, IS_ADMIN, MEM_BIRTH)VALUES ('M', 0, 'admin@admin', 'admin', '관리자', '0', 'admin', 'Y','1995-03-27'); 

INSERT INTO MEM_INFO (MEM_GENDER, MEM_AGE, MEM_EMAIL, MEM_PASS, MEM_NAME, MEM_TEL1, MEM_ADDR, MEM_BIRTH)VALUES ('M', 26, 'gksdudrms0@naver.com', '123123', '한인식', '010-4654-3480', '울산','1995-03-27'); 


COMMENT ON TABLE MEM_INFO IS '개인회원(회원가입)';

COMMENT ON COLUMN MEM_INFO.MEM_EMAIL IS '이메일(아이디)';

COMMENT ON COLUMN MEM_INFO.MEM_PASS IS '회원 비밀번호';

COMMENT ON COLUMN MEM_INFO.MEM_NAME IS '이름';

COMMENT ON COLUMN MEM_INFO.MEM_AGE IS '나이';

COMMENT ON COLUMN MEM_INFO.MEM_GENDER IS '성별';

COMMENT ON COLUMN MEM_INFO.MEM_BIRTH IS '생년월일';

COMMENT ON COLUMN MEM_INFO.MEM_TEL1 IS '연락처1(휴대폰)';

COMMENT ON COLUMN MEM_INFO.MEM_TEL2 IS '연락처2(집전화)';

COMMENT ON COLUMN MEM_INFO.MEM_ADDR IS '주소';

COMMENT ON COLUMN MEM_INFO.DEL_YN IS '회원탈퇴여부';

COMMENT ON COLUMN MEM_INFO.MEM_JOIN_DATE IS '가입날짜';

COMMENT ON COLUMN MEM_INFO.IS_ADMIN IS '관계자여부';

COMMENT ON COLUMN MEM_INFO.MEM_IMAGE IS '증명사진';

-------------------------------------------------------------------------------------

-- 이력서 모음
CREATE TABLE MEM_RESUME(
    RESUME_NUM      NUMBER       NOT NULL,
    RESUME_NAME     VARCHAR2(40) NOT NULL,
    RESUME_DATE     DATE         DEFAULT SYSDATE,
    EDU_GRADE       VARCHAR2(100) NOT NULL,
    EDU_SCHOOL      VARCHAR2(100) NOT NULL,
    EDU_LOC         VARCHAR2(100) NOT NULL,
    EDU_TYPE        VARCHAR2(100) NOT NULL,
    EDU_MAJOR       VARCHAR(100)  NOT NULL,
    EDU_BEGIN_DATE  VARCHAR2(100) NOT NULL,
    EDU_END_DATE    VARCHAR2(100) NULL,
    EDU_IS_OVER     VARCHAR2(100) NULL,
    EDU_SCORE       NUMBER       NULL,
    BE_COMPANY      VARCHAR2(100) NOT NULL,
    BE_CAREER       NUMBER       NOT NULL,
    BE_TYPE         VARCHAR2(100) NOT NULL,
    BE_POSITION     VARCHAR2(100) NOT NULL,
    HOPE_TYPE       VARCHAR2(100) DEFAULT '없음',
    HOPE_SAL        NUMBER       DEFAULT '0',
    HOPE_LOC        VARCHAR2(100) DEFAULT '없음',
    HOPE_TIME       VARCHAR2(100) DEFAULT '주 5일',
    MEM_EMAIL       VARCHAR2(100) NOT NULL,
    CONSTRAINT RESUME_PK PRIMARY KEY (RESUME_NUM),
    CONSTRAINT FK_RESUME_EMAIL FOREIGN KEY (MEM_EMAIL) REFERENCES MEM_INFO (MEM_EMAIL)
);

COMMENT ON TABLE MEM_RESUME IS '이력서 모음';
COMMENT ON COLUMN MEM_RESUME.RESUME_NUM IS '이력서 식별번호';
COMMENT ON COLUMN MEM_RESUME.RESUME_NAME IS '이력서 제목';
COMMENT ON COLUMN MEM_RESUME.RESUME_DATE IS '이력서 갱신일';
COMMENT ON COLUMN MEM_RESUME.EDU_GRADE IS '학력';
COMMENT ON COLUMN MEM_RESUME.EDU_SCHOOL IS '학교';
COMMENT ON COLUMN MEM_RESUME.EDU_LOC IS '지역';
COMMENT ON COLUMN MEM_RESUME.EDU_TYPE IS '전공';
COMMENT ON COLUMN MEM_RESUME.EDU_MAJOR IS '학과';
COMMENT ON COLUMN MEM_RESUME.EDU_BEGIN_DATE IS '재학기간';
COMMENT ON COLUMN MEM_RESUME.EDU_END_DATE IS '졸업기간';
COMMENT ON COLUMN MEM_RESUME.EDU_IS_OVER IS '졸업여부';
COMMENT ON COLUMN MEM_RESUME.EDU_SCORE IS '학점';
COMMENT ON COLUMN MEM_RESUME.BE_COMPANY IS '이전회사명';
COMMENT ON COLUMN MEM_RESUME.BE_CAREER IS '경력기간';
COMMENT ON COLUMN MEM_RESUME.BE_TYPE IS '경력직종';
COMMENT ON COLUMN MEM_RESUME.BE_POSITION IS '경력직책';
COMMENT ON COLUMN MEM_RESUME.HOPE_TYPE IS '희망직종';
COMMENT ON COLUMN MEM_RESUME.HOPE_SAL IS '희망급여';
COMMENT ON COLUMN MEM_RESUME.HOPE_LOC IS '희망근무지';
COMMENT ON COLUMN MEM_RESUME.HOPE_TIME IS '희망근무시간';
COMMENT ON COLUMN MEM_RESUME.MEM_EMAIL IS '이메일(FK)';

INSERT INTO MEM_RESUME VALUES (1, '한인식의 이력서', SYSDATE, '대학교(4년제)', '울산과학대학교', '울산', '공학계열', '전기학과', '2014-03-01', '2020-02-14', '졸업', 3.9, '삼미기계', '2', '생산.제조', '조립', '프로그래밍', '10000', '서울', '주3일', 'gksdudrms0@naver.com');




----------------------------------------------------------------------------

--자격증 DB
CREATE TABLE LICENSE(
    LIC_NUM NUMBER NULL,
    LIC_NAME VARCHAR2(100) NOT NULL,
    LIC_LOC VARCHAR2(100) NOT NULL,
    LIC_GRADE VARCHAR2(100) NOT NULL,
    LIC_DATE DATE NOT NULL,
    RESUME_NUM NUMBER NOT NULL,
    CONSTRAINT LIC_NUM_PK PRIMARY KEY (LIC_NUM),
     CONSTRAINT FK_LICENSE_RESUME FOREIGN KEY (RESUME_NUM) REFERENCES MEM_RESUME (RESUME_NUM)
);

COMMENT ON TABLE LICENSE IS '자격증';
COMMENT ON COLUMN LICENSE.LIC_NUM IS '자격증식별번호';
COMMENT ON COLUMN LICENSE.LIC_NAME IS '자격증명';
COMMENT ON COLUMN LICENSE.LIC_LOC IS '자격증발급처';
COMMENT ON COLUMN LICENSE.LIC_GRADE IS '자격증점수';
COMMENT ON COLUMN LICENSE.LIC_DATE IS '자격증취득일';
COMMENT ON COLUMN LICENSE.RESUME_NUM IS '이력서번호(FK)';

INSERT INTO LICENSE VALUES (1, 'JLPT', '일본국제교육지원협회', 'N1', '2018-08-19', 1);
INSERT INTO LICENSE VALUES (2, 'TOEIC', 'YBM', '645', '2020-02-14', 1);
---------------------------------------------------------------

--자기소개서 DB
CREATE TABLE PROFILES(
    PRO_NUM NUMBER NOT NULL,
    PRO_TITLE VARCHAR2(100) NOT NULL,
    PRO_CONTENT VARCHAR2(1000) NOT NULL,
    RESUME_NUM NUMBER NOT NULL,
    CONSTRAINT PRO_NUM_PK PRIMARY KEY (PRO_NUM),
    CONSTRAINT FK_PROFILES_RESUME FOREIGN KEY (RESUME_NUM) REFERENCES MEM_RESUME (RESUME_NUM)
);

COMMENT ON TABLE PROFILES IS '자기소개서';
COMMENT ON COLUMN PROFILES.PRO_NUM IS '자기소개서식별번호';
COMMENT ON COLUMN PROFILES.PRO_TITLE IS '제목';
COMMENT ON COLUMN PROFILES.PRO_CONTENT IS '내용';
COMMENT ON COLUMN PROFILES.RESUME_NUM IS '이력서번호(FK)';

INSERT INTO PROFILES VALUES(1, '나는 한인식이다', '제목과 동일', 1);
INSERT INTO PROFILES VALUES(2, '나는 한인식인가?', '제목과 동일', 1);
--------------------------------------------------------------------------------
COMMIT;