-- 공지 사항

CREATE TABLE NOTICE(
    NOTICE_NUM      NUMBER          NOT NULL,
    NOTICE_TITLE    VARCHAR2(100)   NOT NULL,
    NOTICE_CONTENT  VARCHAR2(100)   NOT NULL,
    MEM_EMAIL       VARCHAR2(100)   NOT NULL,
    NOTICE_VIEWS    NUMBER          DEFAULT 0,
    CONSTRAINT NOTICE_PK PRIMARY KEY (NOTICE_NUM),
    CONSTRAINT FK_NOTICE_EMAIL FOREIGN KEY (MEM_EMAIL) REFERENCES MEM_INFO (MEM_EMAIL)
);